export const MARKET_CATEGORIES = {
  phones: {
    id: "phones",
    labelKey: "nav_duka_tech_label",
    emoji: "📱",
    color: "#3b82f6",
    gradient: "linear-gradient(135deg,#1e3a5f,#0a1628)",
    brands: ["iPhone","Samsung","Tecno","Infinix","Xiaomi","Oppo","Vivo","Huawei","Nokia","Google Pixel"],
    subcategories: ["Button Phones"],
  },
  laptops: {
    id: "laptops",
    labelKey: "nav_duka_acc_label",
    emoji: "💻",
    color: "#8b5cf6",
    gradient: "linear-gradient(135deg,#2d1b4e,#120a28)",
    brands: ["HP","Dell","Lenovo","Apple MacBook","ASUS","Acer","MSI"],
    subcategories: ["Student Laptops","Business Laptops"],
  },
  accessories: {
    id: "accessories",
    labelKey: "nav_duka_assets_label",
    emoji: "🎧",
    color: "#10b981",
    gradient: "linear-gradient(135deg,#0d3526,#051a13)",
    subcategories: ["Phone Accessories","Computer Accessories","Smart Gadgets","Car Accessories","Gaming Accessories"],
    subItems: {
      "Phone Accessories": ["Chargers","Fast Chargers","Type-C Cables","iPhone Cables","Power Banks","Earphones","Wireless Earbuds","Phone Cases","Screen Protectors","Phone Holders"],
      "Computer Accessories": ["Mouse","Keyboard","Laptop Bags","Cooling Pads","Flash Drives","USB Hubs","External Hard Drives","Webcams"],
      "Smart Gadgets": ["Smart Watches","Fitness Bands","Bluetooth Speakers","Ring Lights","Tripods"],
      "Car Accessories": ["Car Chargers","Car Phone Holders","FM Transmitters","Dash Cameras"],
      "Gaming Accessories": ["Gaming Mouse","Gaming Keyboard","Headsets","Controllers"],
    },
  },
  furniture: {
    id: "furniture",
    labelKey: "nav_duka_sell_label",
    emoji: "🪑",
    color: "#f59e0b",
    gradient: "linear-gradient(135deg,#3d2910,#1a1005)",
    subcategories: ["Sofa","Beds","Mattresses","Tables","Chairs","Wardrobes","TV Stands","Dining Sets","Office Furniture","Shelves"],
  },
  beauty: {
    id: "beauty",
    labelKey: "nav_duka_dash_label",
    emoji: "💄",
    color: "#ec4899",
    gradient: "linear-gradient(135deg,#4a1532,#200a18)",
    subcategories: ["Perfumes","Body Lotions","Body Oils","Soaps","Hair Products","Skincare","Makeup","Lipsticks"],
  },
};
